# Generated by Django 2.0.6 on 2018-06-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiseq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(max_length=100)),
                ('paired_end', models.CharField(max_length=100)),
                ('flowcell_version', models.CharField(max_length=100)),
                ('sbs_version', models.CharField(max_length=100)),
                ('pe_version', models.CharField(max_length=100)),
                ('index_version', models.CharField(max_length=100)),
                ('clustering_choice', models.CharField(max_length=100)),
                ('rapid_run_chemistry', models.CharField(max_length=100)),
                ('run_mode', models.CharField(max_length=100)),
                ('application_name', models.CharField(max_length=100)),
                ('application_version', models.CharField(max_length=100)),
                ('FPGA_version', models.CharField(max_length=100)),
                ('CPLD_version', models.CharField(max_length=100)),
                ('RTA_version', models.CharField(max_length=100)),
                ('chemistry_version', models.CharField(max_length=100)),
                ('camera_firmware', models.CharField(max_length=100)),
                ('camera_driver', models.CharField(max_length=100)),
                ('sbs_reagent_kit', models.CharField(max_length=100)),
                ('index_reagent_kit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Miseq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCS_version', models.CharField(max_length=100)),
                ('RTA_version', models.CharField(max_length=100)),
                ('flowcell_serial_no', models.CharField(max_length=100)),
                ('flowcell_part_no', models.CharField(max_length=100)),
                ('flowcell_expiry', models.CharField(max_length=100)),
                ('PR2_serial_no', models.CharField(max_length=100)),
                ('PR2_part_no', models.CharField(max_length=100)),
                ('PR2_expiry', models.CharField(max_length=100)),
                ('reagent_serial_no', models.CharField(max_length=100)),
                ('reagent_part_no', models.CharField(max_length=100)),
                ('reagent_expiry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Runlog',
            fields=[
                ('run_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('instrument', models.CharField(max_length=100)),
                ('instrument_date', models.DateField()),
                ('num_cycles1', models.IntegerField()),
                ('num_cycles2', models.IntegerField()),
                ('investigator', models.CharField(max_length=100, null=True)),
                ('experiment', models.CharField(max_length=100, null=True)),
                ('samplesheet_date', models.DateField(null=True)),
                ('workflow', models.CharField(max_length=100, null=True)),
                ('application', models.CharField(max_length=100, null=True)),
                ('assay', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('chemistry', models.CharField(max_length=100, null=True)),
                ('plates', models.CharField(max_length=200, null=True)),
                ('pipeline', models.CharField(max_length=200, null=True)),
                ('percent_Q30', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('cluster_density', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('percent_pf', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('phasing', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('prephasing', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('error_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('percent_aligned', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='miseq',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Runlog'),
        ),
        migrations.AddField(
            model_name='hiseq',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Runlog'),
        ),
    ]
