# Generated by Django 2.0.6 on 2018-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiseq',
            name='pe_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
