# Generated by Django 2.0.6 on 2018-06-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180629_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiseq',
            name='pe_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='application',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='assay',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='chemistry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='experiment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='investigator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='pipeline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='plates',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='samplesheet_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='workflow',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
