# Generated by Django 2.0.6 on 2018-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20180703_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='description2',
            field=models.TextField(null=True),
        ),
    ]
