# Generated by Django 2.0.6 on 2018-07-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_runlog_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='diagnostic_run',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runlog',
            name='sensitivity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='runlog',
            name='sensitivity_lower_95ci',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='runlog',
            name='sensitivity_upper_95ci',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
