# Generated by Django 2.0.6 on 2018-07-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20180705_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='setup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='diagnostic_run',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='pipeline',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='plates',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='samplesheet_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
