# Generated by Django 2.0.6 on 2018-07-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20180706_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='pipeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
